from django.urls import path
from mapbox.views import (
    InteractiveLineStringFieldAddView,
    InteractiveLineStringFieldEditView,
    InteractiveLineStringFieldListView,
    InteractiveMultiPolygonFieldAddView,
    InteractiveMultiPolygonFieldEditView,
    InteractiveMultiPolygonFieldListView,
    InteractivePointFieldAddView,
    InteractivePointFieldEditView,
    InteractivePointFieldListView,
    InteractivePolygonFieldAddView,
    InteractivePolygonFieldEditView,
    InteractivePolygonFieldListView,
    StaticPointFieldEditView,
    StaticPointFieldListView,
)

app_name = "mapbox"

urlpatterns = [
    path(
        "pointfield/interactive/",
        InteractivePointFieldListView.as_view(),
        name="pointfield_interactive_list",
    ),
    path(
        "pointfield/interactive/<int:pk>/",
        InteractivePointFieldEditView.as_view(),
        name="pointfield_interactive_edit",
    ),
    path(
        "pointfield/interactive/add/",
        InteractivePointFieldAddView.as_view(),
        name="pointfield_interactive_add",
    ),
    path(
        "pointfield/static/",
        StaticPointFieldListView.as_view(),
        name="pointfield_static_list",
    ),
    path(
        "pointfield/static/<int:pk>/",
        StaticPointFieldEditView.as_view(),
        name="pointfield_static_edit",
    ),
    path(
        "linestringfield/interactive/",
        InteractiveLineStringFieldListView.as_view(),
        name="linestringfield_interactive_list",
    ),
    path(
        "linestringfield/interactive/<int:pk>/",
        InteractiveLineStringFieldEditView.as_view(),
        name="linestringfield_interactive_edit",
    ),
    path(
        "linestringfield/interactive/add/",
        InteractiveLineStringFieldAddView.as_view(),
        name="linestringfield_interactive_add",
    ),
    path(
        "polygonfield/interactive/",
        InteractivePolygonFieldListView.as_view(),
        name="polygonfield_interactive_list",
    ),
    path(
        "polygonfield/interactive/<int:pk>/",
        InteractivePolygonFieldEditView.as_view(),
        name="polygonfield_interactive_edit",
    ),
    path(
        "polygonfield/interactive/add/",
        InteractivePolygonFieldAddView.as_view(),
        name="polygonfield_interactive_add",
    ),
    path(
        "multipolygonfield/interactive/",
        InteractiveMultiPolygonFieldListView.as_view(),
        name="multipolygonfield_interactive_list",
    ),
    path(
        "multipolygonfield/interactive/<int:pk>/",
        InteractiveMultiPolygonFieldEditView.as_view(),
        name="multipolygonfield_interactive_edit",
    ),
    path(
        "multipolygonfield/interactive/add/",
        InteractiveMultiPolygonFieldAddView.as_view(),
        name="multipolygonfield_interactive_add",
    ),
]
